services:
  web:
    build: .
    container_name: ai-text-detector
    ports:
      - "5000:5000"
    volumes:
      - ./notebooks:/app/notebooks
      - ./templates:/app/templates
      - ./static:/app/static
      - ./app.py:/app/app.py
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
