services:
  jupyter:
    build: .
    container_name: ai-text-detector
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    restart: unless-stopped
