version: '3'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
